# SPDX-License-Identifier: Apache-2.0
[workspace]
members = [
    "belvi_ct_scan",
    "belvi_log_list",
    "belvi_render",
    "belvi_hash",
    "belvi_frontend",
    "belvi_cache",
]

[profile.release]
lto = true
codegen-units = 1
debug = 2
