# SPDX-License-Identifier: Apache-2.0
[package]
name = "belvi_db"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.27.0", features = ["functions"] }
regex = "1.5.5"
log = "0.4.14"
